version: '3.8'

services:
  postgres:
    image: postgres:${POSTGRES_VERSION:-18.3}
    container_name: terminals_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"  # Хост:Контейнер
    volumes:
      # 1. volume для сохранения данных (persistence)
      - ./docker/postgres/data:/var/lib/postgresql
      # 2. Bind mount для скриптов инициализации
      - ./docker/postgres/init:/docker-entrypoint-initdb.d
    networks:
      - terminals-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

# Определение сети
networks:
  terminals-network:
    driver: bridge