// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using StranaKart.Assignment.Infrastructure;

#nullable disable

namespace StranaKart.Assignment.Infrastructure.Migrations
{
    [DbContext(typeof(DellinDictionaryDbContext))]
    [Migration("20260309122607_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("StranaKart.Assignment.Domain.Entities.Office", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<int?>("AddressApartment")
                        .HasColumnType("integer")
                        .HasColumnName("address_apartment");

                    b.Property<string>("AddressCity")
                        .HasColumnType("text")
                        .HasColumnName("address_city");

                    b.Property<string>("AddressHouseNumber")
                        .HasColumnType("text")
                        .HasColumnName("address_house_number");

                    b.Property<string>("AddressRegion")
                        .HasColumnType("text")
                        .HasColumnName("address_region");

                    b.Property<string>("AddressStreet")
                        .HasColumnType("text")
                        .HasColumnName("address_street");

                    b.Property<string>("CityCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("city_code");

                    b.Property<string>("Code")
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("country_code");

                    b.Property<int?>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<Guid?>("Uuid")
                        .HasColumnType("uuid")
                        .HasColumnName("uuid");

                    b.Property<string>("WorkTime")
                        .HasColumnType("text")
                        .HasColumnName("work_time");

                    b.HasKey("Id")
                        .HasName("pk_offices");

                    b.HasIndex("AddressCity")
                        .HasDatabaseName("ix_offices_address_city");

                    b.HasIndex("CityCode")
                        .HasDatabaseName("ix_offices_city_code");

                    b.HasIndex("Uuid")
                        .IsUnique()
                        .HasDatabaseName("ix_offices_uuid");

                    b.HasIndex("AddressCity", "Type")
                        .HasDatabaseName("ix_offices_address_city_type");

                    b.HasIndex("CityCode", "Type")
                        .HasDatabaseName("ix_offices_city_code_type");

                    b.ToTable("offices", (string)null);
                });

            modelBuilder.Entity("StranaKart.Assignment.Domain.Entities.OfficePhone", b =>
                {
                    b.Property<int>("OfficeId")
                        .HasColumnType("integer")
                        .HasColumnName("office_id");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<string>("Additional")
                        .HasColumnType("text")
                        .HasColumnName("additional");

                    b.HasKey("OfficeId", "PhoneNumber")
                        .HasName("pk_office_phones");

                    b.ToTable("office_phones", (string)null);
                });

            modelBuilder.Entity("StranaKart.Assignment.Domain.Entities.Office", b =>
                {
                    b.OwnsOne("StranaKart.Assignment.Domain.Entities.Coordinates", "Coordinates", b1 =>
                        {
                            b1.Property<int>("OfficeId")
                                .HasColumnType("integer")
                                .HasColumnName("id");

                            b1.Property<double?>("Latitude")
                                .HasColumnType("double precision")
                                .HasColumnName("latitude");

                            b1.Property<double?>("Longitude")
                                .HasColumnType("double precision")
                                .HasColumnName("longitude");

                            b1.HasKey("OfficeId");

                            b1.ToTable("offices");

                            b1.WithOwner()
                                .HasForeignKey("OfficeId")
                                .HasConstraintName("fk_offices_offices_id");
                        });

                    b.Navigation("Coordinates");
                });

            modelBuilder.Entity("StranaKart.Assignment.Domain.Entities.OfficePhone", b =>
                {
                    b.HasOne("StranaKart.Assignment.Domain.Entities.Office", null)
                        .WithMany("Phones")
                        .HasForeignKey("OfficeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_office_phones_offices_office_id");
                });

            modelBuilder.Entity("StranaKart.Assignment.Domain.Entities.Office", b =>
                {
                    b.Navigation("Phones");
                });
#pragma warning restore 612, 618
        }
    }
}
